### PR TITLE
Release 0.0.9 for 3.9.3.1986

### LINKED ISSUE #66: Feature request: Make Lamy tool switch action configurable
I find that the ability to press the button on the Lamy pen to switch tools is a bit annoying, since sometimes it won't register my use of the eraser correctly and I'll end up with the wrong tool after erasing. Can a toggle be added to the settings to turn that functionality off while keeping the eraser working?

Same as this issue, but with these new rm-hacks instead of the ddvk remarkable-hacks: https://github.com/ddvk/remarkable-stylus/issues/8

### LINKED ISSUE #71: Name of color abbreviated in the top corner
It would be great to have an actual indication of the pen/highlighter color next to its corresponding circle when the toolbar’s closed. Or even better, inside the circle if made big enough.

I suggest something like what Boox uses on their devices: BK, GY, WT, BU, RD for the pen. YL, GN, PK, GY for the highlighter.

### LINKED ISSUE #88: Feature request: Option for less obtrusive tool icon (50x50 area instead of 100x100)
I got used to the ddvk hacks which packed the tool icon into roughly 50x50 pixels in the very corner of the screen. The rm-hacks claim the same icon area as the native firmware, which seems to be 100x100 pixels or four times larger than ddvk. 

From ddvk I am used to using the top left corner of the page for dates, etc, and I don't like the obtrusive icon and its larger hitbox. Would it be possible to add an option for less obtrusive tool icon?

Below are screenshots from ddvk and from rm-hacks 0.0.7 along with a mockup that keeps the large color swatch, but packs it into a smaller 50x50 px area like ddvk.

Current rm-hacks marker icon 100x100:
231211_rm-hacks_tool-icon_100x100

Mockup of same marker icon packed into 50x50:
231211_rm-hacks_tool-icon_50x50_packed

ddvk screenshot with eraser icon:
231123_2 15ddvk_Toolbar closed

rm-hacks screenshot with eraser icon:
231211_3 8x_rm-hacks0 0 7_Toolbar closed_eraser

Please consider this.
But regardless, thank you for all the work you have done!

### LINKED ISSUE #95: Feature request: Fake keyboard connection in order to get the whole interface in landscape mode
I was taking a look over cache qmlc file with hex editor and I found this:
SavedDeviceInfo.keyboardConnected&window{DeviceInfo.keyboardConnected 

and i was wondering if there is a way to fake that connection

### LINKED ISSUE #108: Feature request: Notebook New Page - added automatically
It would be amazing to have a new page added when I swipe the last page of the notebook, instead of also hitting the new page button.

### LINKED ISSUE #116: Bug: hidden text when awaking from light sleep
I often have missing hand-written texts or drawings when I awake my rM1 from light sleep (i.e., when the text "...zzzZ" is displayed).

The missing elements do not appear if I start writting or if I use the refresh shortcut (the one with the 5 fingers). 
However, it appears if 
- I turn the page and come back or 
- after some time (in this second case, I usually have not realised that something was missing and I wrote on top of it, which is not very pratical).

I am surprised that no one reported this bug. Maybe it is specific to the rm1... 
If the bug is not clear, I can try to make a video next time it happens.

### LINKED ISSUE #129: Button to jump directly to tags page (and a big thanks for the wonderful hacks)
The bookmarks are essential for quickly navigating pages within the same document.
If there was a button for jumping directly to the tags page this will make navigating pages across documents.
The button could be in a menu or the tool bar or even in the "View All" in the tags popup.

### LINKED ISSUE #132: Small fix: Bookmark tap area when disabled still not writable
It seems that with the new feature for bookmarks in v0.0.8 there is the following issue:
1. Disable the "Tap in corner opposite of toolbar to set bookmark" feature in settings
2. Then the area where this bookmark tap would happen is still not writable in documents

Do you think this is something that could be addressed?

Thanks and thanks so much in general for those wonderful hacks!!

### LINKED ISSUE #138: Hide toolbar toggle icon completely when it is not active
Hi,

Thank you for your wonderful hacks.

Would it be possible to hide the toolbar toggle icon completely when it is not active.
Sometimes it blocks some of the letters of the text I am reading.

I think there was a similar feature in the ddvk hacks which was called Zen mode.  It was hiding all the icons and making it posssbile to turn pages by tapping on the right or left side of the page.

Thanks again for these hacks, you are doing a great work.

### LINKED ISSUE #145: File size and page count not readable in compressed list with Large font
When the Accessibility setting is set to the Large font size, the compressed list should be adjusted:

image

### LINKED ISSUE #218: Bookmarks orphaned after moving pages out of Notebook
I had 2 pages with bookmarks. I selected them and moved them out of the Notebook. The bookmarks still exist as page “0”. I can’t find a way to delete them.

IMG_8429

rm-hacks  v0.0.8
rM version 3.9.3.1986

### PR DESCRIPTION
**Pull request by mb1986**
Hello Everyone,

I am happy to announce that version 0.0.9 is finally ready for public release. :wink:
It contains many new features, including @atngames's Quick Tools, numerous bug fixes, and probably some new bugs as well.

**To test it, simply run:**

```sh
bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/release/v0.0.9-3.9.3.1986/install.sh -O-)" _ patch 0.0.9-alpha.14
```

---

> #### New features:
> 
> - Add button at the top of documents list to trigger screen orientation change (closes #95).
> - Remove the need to confirm by tapping the button after swiping right to add a new page (closes #108).
> - Remove the last empty page when navigating to the previous one.
> - Long press on the toolbar tags button to jump straight into Menu/Tags view (closes #129).
> - Add colors abbreviations to the color icon (near the brush icon) (closes #71).
> - Persist tags selection for filtering in Menu/Tags view (closes #129).
> - Double tap the document:
>   - in the middle to remove current and empty page,
>   - on the left-hand side (up to about 3cm from the edge) to add a new empty page before the current one,
>   - on the right-hand side (up to about 3cm from the edge) to add a new empty page after the current one.
> - Decrease the size of both the brush icon and toolbar width to 75% of their original sizes (closes #88).
> - Add configuration options for various click and press behaviors of the stylus button (closes #66).
> - Add a quicktools bar to store shortcut to tools. Swipe up to show / hide. double tap to remove a tool or to move it.
> - Add a setting to hide the document toggle for toolbar (closes #138)
> - Add a setting to hide the toolbar header (the round toggle to fullscreen)
> 
> #### Bug fixes:
> 
> - Fix wrong margins in compressed documents list view when large font is selected (closes #145).
> - Fix writing experience in the corner where bookmark button/icon is located (closes #132).
> - Fixed issue with keyboard appearing when a PDF is opened after a restart (see #179).
> - Fix foldouts too wide in toolbar compressed width (see #156).
> - Fix Tags in the compressed list overlap the document names (see #157).
> - Remove orphaned bookmarks when pages has been (re)moved (closes #218).
> 
> #### Other changes:
> 
> - Move the bookmark rename input into the header at the top of the screen (see #127).
> - Move the bookmarks toolbar button between the tags and layers buttons (see #127).
> - Fix native rM1 bug hiding drawings when going to light sleep (closes #116).

### CODE REVIEW

**Comment by PepikVaio** [comment]
#95
Add the ability to select the direction of rotation and long press to revert to normal mode.

**Comment by PepikVaio** [comment]
Quick tool: (bugs)
1. When I set something about the quick tool and then turn the whole quick tool off, I still see the quick tool settings (close and open button) and then it does nothing - big bug!
2. When opening and closing, the button image does not change like the original one.
3. When I have a vertical view and want to move the tool, I have a choice of left and right and it should be up and down.
4. When I have the gesture view turned off, and selecting horizontal view and selecting as Castle, it hides the reMarkable ball and I have no way to get the menu back - big mistake!

**Comment by atngames** [comment]
Okay I think I fixed completely #88 and number 1 3 and 4 of the previous comment. Thanks @PepikVaio to raise those.
@mb1986 I'll PR those now

**Comment by Kelvin88** [comment]
This patch fixed 👍 bug in alpha 10 where hidden quick tool didn’t  show up after toolbar is dismissed.

**Comment by PepikVaio** [comment]
#88 still moving :(https://github.com/mb1986/rm-hacks/assets/36114753/9fbebc80-1cda-419e-8b66-ad89f412aec2

**Comment by atngames** [comment]
> Alpha 12
> 
> #88 still moving :(
> 
> Bugs: 1, 3, 4 - not fix
> 
> Ok, maybe this is not implement in alpha 12? https://github.com/mb1986/rm-hacks/assets/36114753/9fbebc80-1cda-419e-8b66-ad89f412aec2

Nope, there was an error in the code.
Will come soon

**Comment by atngames** [comment]
There we go, hopefully :D

**Comment by PepikVaio** [comment]
Alpha 13 bugs
#88 - still moving (but less)

But look at this:
https://github.com/mb1986/rm-hacks/assets/36114753/c1deb866-61c2-47b4-813c-78df443cf70e

**Comment by atngames** [comment]
You have a gift for this :D

@mb1986 I pushed force some fixes for those three bugs. Never been this close!

**Comment by atngames** [comment]
These should be fixed in alpha 14:
`bash -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.9-alpha.14`
Could you confirm ?

**Review by atngames — APPROVED** [review]

**Comment by mb1986** [comment]
Thank you for the testing! It is already merged - released :gift:

**Pull request merged**
