### PR TITLE
Prepare v0.0.7 release for 3.8.3.1976

### LINKED ISSUE #68: New 3.8.3.1976
Hi guys, I found this repo through Reddit. But when I looked at the version of my RM2, it asked me to reboot for the auto update. I rebooted and the version is now 3.8.3.1976.

Can I try to install it? It is compatible? Do I risk something?

### PR DESCRIPTION
**Pull request by mb1986**
Thanks to @ard0gg I am able to bring  **v0.0.7** to **rM2** devices updated to **3.8.3.1976**.

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.7
```

It is already ready for testing!

Closes #68

### CODE REVIEW

**Comment by Eeems** [comment]
Just in time for 3.9.3.1986 to be released :P

**Comment by mb1986** [comment]
> Just in time for 3.9.3.1986 to be released :P

It is never ending story :laughing:

**Comment by PepikVaio** [comment]
I think it would be better to turn off these small updates and wait for the bigger ones.

After all, even 3.9 brings almost nothing.

**Comment by Eeems** [comment]
> I think it would be better to turn off these small updates and wait for the bigger ones.
> 
> After all, even 3.9 brings almost nothing.

I think you'll find that other people want to always have the latest release with all the fixes. You even have [people asking for support on the beta releases, which will not happen](https://github.com/mb1986/rm-hacks/issues/67).

**Comment by PepikVaio** [comment]
I understand but @mb1986 can't do updates and patches at the same time.

I appreciate the time he puts into it but updates keep him from working.

**Comment by mb1986** [comment]
> I understand but @mb1986 can't do updates and patches at the same time.
> 
> I appreciate the time he puts into it but updates keep him from working.

Hahaha, mb1986 the worker :D I've made my day man!

**Comment by PepikVaio** [comment]
I don't have 3.8.3.1976.
I can not test.

**Comment by Eeems** [comment]
> I don't have 3.8.3.1976. I can not test.

https://remarkable.guide/faqs.html#can-i-downgrade-to-a-different-os-version

**Comment by PepikVaio** [comment]
Yes, I know how to get the version I need into rm but this weekend I played with it all day and tried 2.15 and toltec that now I want to enjoy a little peace and let reMarkable breathe :)

That's why I disabled updates so I wouldn't lose the hacks.

However, if needed (no one can be found), I can test it.

**Comment by ard0gg** [comment]
<details>
  <summary>Regression Checklist</summary>

# Purpose
This document is meant to serve as a checklist for items to perform regression testing on when new RM-Hacks releases are pushed for testing.
# Device: RM2
# Tests
## Basic Functions
- [x] Notebooks can be opened
  - [x] Can write in notebook
- [x] PDFs can be opened
  - [x]  Can write in PDF
- [x] Ebooks can be opened
  - [x] Can write in Ebook
## RM-Hacks
### UI
- [x] The close icon (x) in the top right corner (right-handed)/left corner (left-handed) has been removed. You can still close the document by swiping one finger down from the top.
- [x] The toolbar icon changes from the default open icon to a brush icon.
- [x] Additional stroke sizes (0.5, 1.5, 5, 8, 13).
  - [x] Fewer stroke sizes for the eraser compared to other tools, and fixed eraser stroke sizes panel overflow.
- [x] A brand new settings page to configure which hacks should be enabled and which should not (Menu ⇝ Settings ⇝ rM Hacks). By default, all the hacks are enabled, and the configuration will be preserved between restarts
  - [x] Better placement of the back button on hacks configuration views.
  - [x] Configuration setting to disable the hack that adds additional stroke sizes.
- [x] Document-level clock moved from the bottom to the top of the toolbar.
  - [x] Configuration items may be scrolled vertically.
- [x] Document-level toggle buttons (accessible through the Share and Convert menu):
  - [x] Changed names of document-level toggles (i.e. remove "Disabled" and "Enabled" words).
  - [x] Show/hide clock
    - [x] Make clock toggle option permanent between restarts. 
  - [x] Suppress all swipes and gestures
  - [x] Toggle WiFi
  - [ ] Disable/enable rM1 buttons
  - [x] Toggle automatic updates
- [x] Pen thickness and color indicator show only for the tools that make use of them.
- [x] Toolbar button showing the current page and the page count, clicking it opens fast page scroll.
- [x] Battery level and WiFi signal strength indicators available on the bottom of the toolbar.
- [x] Additional table-of-contents toolbar button.
- [x] Display ...zzZ in the top right corner during light sleep mode instead of a big black banner.

### Gestures
- [x] The toolbar may be opened or closed with a one-finger swipe down.
- [x] Gesture to switch between the writing tool and eraser: swipe one finger up in the top left corner (right-handed)/right corner (left-handed).
  - [x] Taller area for the writing tool/eraser switch gesture. 
:x: Gesture to switch between the last two tools: swipe one finger down in the top left corner (right-handed)/right corner (left-handed).
  Observation: Possible existing bug. When "More Stroke Sizes" is disabled, gesture no longer switches.
- [x] Gesture to swap the last two colors by swiping one finger up in the top right corner (right-handed)/left corner (left-handed).
- [x] Gesture to swap the last two pen thicknesses (strokes) by swiping one finger down in the top right corner (right-handed)/left corner (left-handed).
- [x] Cycle between two recent documents by swiping two fingers up from the bottom of the page.
- [x] Screen refresh trigger via five-finger tap - natively available but disabled by experimental flag.
- [x] Enable sleep mode by swiping up from the top of the screen (light or deep sleep selectable in Settings/Security).

### File Creation
- [x] New notebook name defaults to the current date and time (format: yyyy-mm-dd_hhmmss).

### Lamy Pen 
:x: The Lamy button, in addition to erasing when pressed, toggles the last two tools when clicked
   Observation: Possible existing bug. When "More Stroke Sizes" is disabled, toggle does not always switch tools. Sometimes it takes 2-4 clicks to toggle the tool. 
:x: Lamy button double-click now triggers an undo action.
   Observation: Possible exisiting bug. When "More Stroke Sizes" is disabled, double-click does not always undo.
### Staedtler Pencil
- [ ] Staedtler pencil eraser support (hopefully).
</details>

Most things worked as expected. I think I may have found an existing bug. When "More Stroke Sizes" is disabled some of the functions don't always work as expected. See Regression Checklist for full list of items checked: 

### Gestures
  :x: Gesture to switch between the last two tools: swipe one finger down in the top left corner (right-handed)/right corner (left-handed).
  Observation: Possible existing bug. When "More Stroke Sizes" is disabled, gesture no longer switches.
 ### Lamy Pen 
:x: The Lamy button, in addition to erasing when pressed, toggles the last two tools when clicked
   Observation: Possible existing bug. When "More Stroke Sizes" is disabled, toggle does not always switch tools. Sometimes it takes 2-4 clicks to toggle the tool. 
:x: Lamy button double-click now triggers an undo action.
   Observation: Possible exisiting bug. When "More Stroke Sizes" is disabled, double-click does not always undo.

**Comment by babluc** [comment]
> Regression Checklist
> Most things worked as expected. I think I may have found an existing bug. When "More Stroke Sizes" is disabled some of the functions don't always work as expected. See Regression Checklist for full list of items checked:
> 
> ### Gestures
> ❌ Gesture to switch between the last two tools: swipe one finger down in the top left corner (right-handed)/right corner (left-handed). Observation: Possible existing bug. When "More Stroke Sizes" is disabled, gesture no longer switches.
> 
> ### Lamy Pen
> ❌ The Lamy button, in addition to erasing when pressed, toggles the last two tools when clicked Observation: Possible existing bug. When "More Stroke Sizes" is disabled, toggle does not always switch tools. Sometimes it takes 2-4 clicks to toggle the tool. ❌ Lamy button double-click now triggers an undo action. Observation: Possible exisiting bug. When "More Stroke Sizes" is disabled, double-click does not always undo.


I'm seeing the same issues.

**Comment by mb1986** [comment]
@ard0gg, this is great! Thanks for putting time in creating this regression list. I'll try to figure out why strokes number may affect those other features.

**Comment by dreadful-brain** [comment]
FYI
On my device rM2 3.8.3.1976 the install.sh failed installing lamy hack with error:
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer

but same happened when I tried to install ddvks plugin individually.

I worked around by downloading the files manually to my client and uploading them via scp.

**Comment by PepikVaio** [comment]
Maybe the same problem as here?


https://github.com/JBlocklove/remarkable-daily-pdf

**Comment by lepennec** [comment]
Working perfectly on my Remarkable 2 with 3.8.3.1976, including the tool switch gesture when "More stroke sizes" is disabled.

**Comment by ard0gg** [comment]
I think the issue occurs when you have an additional stroke size selected for stylus when disabling "More Stroke Sizes"

**Pull request merged**
