### PR TITLE
Fix stylus library downloading issue

### LINKED ISSUE #107: Wrong url for ddvk/remarkable-stylus lib
> wget "https://github.com/ddvk/remarkable-stylus/releases/download/0.0.3/libqevdevlamyplugin.so" -O /usr/lib/plugins/generic/libqevdevlamyplugin.so this link seems to be the problem

Ah, this will need to be changed to the raw.githubusercontent.com version of the link for it to work.

_Originally posted by @Eeems in https://github.com/mb1986/rm-hacks/issues/104#issuecomment-1861911689_

### PR DESCRIPTION
**Pull request by mb1986**
Closes #107

### CODE REVIEW

**Comment by Eeems** [comment]
It's not best practice to store binaries in a git repository itself. It would probably be better to go down the route of pulling down a wget build that is known to work (like toltec does).

This also means that you'll have to maintain your own fork for remarkable-stylus as time goes on.

**Comment by Eeems** [comment]
Some example code that would fetch wget and use it to download the file
```bash
wget_path=/home/root/.local/share/rm-hacks/wget
wget_remote=http://toltec-dev.org/thirdparty/bin/wget-v1.21.1
wget_checksum=8798fcdabbe560722a02f95b30385926e4452e2c98c15c2c217583eaa0db30fc

if [ -f "$wget_path" ] && ! sha256sum -c <(echo "$wget_checksum  $wget_path") > /dev/null 2>&1; then
    rm "$wget_path"
fi
if ! [ -f "$wget_path" ]; then
    echo "Fetching secure wget"
    # Download and compare to hash
    mkdir -p "$(dirname "$wget_path")"
    if ! wget -q "$wget_remote" --output-document "$wget_path"; then
        echo "Error: Could not fetch wget, make sure you have a stable Wi-Fi connection"
        exit 1
    fi
fi
if ! sha256sum -c <(echo "$wget_checksum  $wget_path") > /dev/null 2>&1; then
    echo "Error: Invalid checksum for the local wget binary"
    exit 1
fi
chmod 755 "$wget_path"
"$wget_path" \
    "https://github.com/ddvk/remarkable-stylus/releases/download/0.0.3/libqevdevlamyplugin.so" \
    -O /usr/lib/plugins/generic/libqevdevlamyplugin.so
```

**Comment by mb1986** [comment]
Thanks, I'll fix it the way you've suggested.

**Comment by mb1986** [comment]
> This also means that you'll have to maintain your own fork for remarkable-stylus as time goes on.

Do you think it'd be a good idea? https://github.com/ddvk/remarkable-stylus/issues/27#issuecomment-1868371884

**Comment by Eeems** [comment]
I would recommend emailing reMarkable's engineering email asking for the new toolchain, and let me know when you get the links. I'll then update https://github.com/Eeems/images/tree/main/images/remarkable-toolchain (The source for https://remarkable.guide/devel/toolchains.html#docker) with the latest toolchain. We can then get a PR added to remarkable-stylus to automatically compile against various toolchains and create a release with the files you need for the OS version, which you can then download.

For the short-term, you can just create a release in your fork and attach the new *.so file to the release.

**Comment by mb1986** [comment]
I've just tested the wget version you've provided and it does not work:

```sh
reMarkable: ~/ /home/root/.local/share/rm-hacks/wget "https://github.com/ddvk/remarkable-stylus/releases/download/0.0.3/libqevdevlamyplugin.so" -O /usr/lib/plugins/generic/libqevdevlamyplugin.so
--2023-12-27 11:09:29--  https://github.com/ddvk/remarkable-stylus/releases/download/0.0.3/libqevdevlamyplugin.so
Resolving github.com... Segmentation fault
```

May it be related to different glibc version?

**Comment by mb1986** [comment]
Thanks, @Eeems, for guiding me to the proper way of resolving this.

**Pull request merged**
