### PR TITLE
Prepare for v0.0.6 release for 3.8.2.1965

### LINKED ISSUE #21: Bring back clock display toggle
DDVK had a toggle switch on the icon at the bottom left to show or hide a clock under that icon.
This was useful to check if the time setting from the rM was correct without having to go into the shell first.

### LINKED ISSUE #33: Feature Request - toggles panel like ddvk
I LOVE ddvk's toggle panel.,  The ability to toggle things on and off is such a help. The ones I use most often are:

- Wifi
- rM1 Buttons
- Swipes

Thanks for considering this, and your great work!

### LINKED ISSUE #41: Eraser issue
I have some issue with eraser (I'm leaving photos). 

image

### LINKED ISSUE #48: Different sensitivity for gestures
Gestures in the top left corner - swipe down works fine. Swipe-up has a very limited area where to start the swipe (e.g. 35mm from top) and there is not much space left for the swipe. Would it be possible to enlarge this area? Hopefully, it won't make a collision with other gestures.

Swipe down is fine since the important things are just starting point and direction.

(rM1, v0.0.5)

Thank you very much for your work! Looking forward to new features.

Cheers, Tomas

### PR DESCRIPTION
**Pull request by mb1986**
- Document-level toggle buttons (accessible through the _Share and Convert_ menu):
  - Show/hide clock
  - Suppress all swipes and gestures
  - Toggle WiFi
  - Disable/enable rM1 buttons
  - Toggle automatic updates
- Cycle between two recent documents by swiping two fingers up from the bottom of the page.
- Gesture to swap the last two pen thicknesses (strokes) by swiping one finger down in the top right corner (right-handed)/left corner (left-handed).
- Gesture to swap the last two colors by swiping one finger up in the top right corner (right-handed)/left corner (left-handed).
- Clock in the bottom of the toolbar.
- Configuration setting to disable the hack that adds additional stroke sizes.
- Staedtler pencil eraser support (hopefully).
- Taller area for the writing tool/eraser switch gesture.
- Better placement of the back button on hacks configuration views.
- Fewer stroke sizes for the eraser compared to other tools, and fixed eraser stroke sizes panel overflow.

Closes #21, closes #33, closes #41, closes #48, adds new gestures to #13.

### CODE REVIEW

**Comment by mb1986** [comment]
The patch v0.0.6 is ready for testing:

```shell
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.6
```

Your feedback is welcome!

**Comment by PepikVaio** [comment]
Great work - I am happy for:
"Cycle between two recent documents by swiping two fingers up from the bottom of the page."
"Better placement of the back button on hacks configuration views."


Note:
I wouldn't write which side the gesture is on, because it's a bit confusing for left-handed people - the bar is on the other side and so are the gestures.

**Comment by PepikVaio** [comment]
**_Please keep turning each newly added feature on and off in the settings.

This is a game changer for me over DDVK - I hardly used it because the bar became messy and confusing (there was too much).

Here I turn on and off everything I don't need and that's awesome._**

**Comment by mb1986** [comment]
> Great work - I am happy for: "Cycle between two recent documents by swiping two fingers up from the bottom of the page." "Better placement of the back button on hacks configuration views."
> 
> Note: I wouldn't write which side the gesture is on, because it's a bit confusing for left-handed people - the bar is on the other side and so are the gestures.

Yes, I fully agree with your note. Let me review the entire README.md and fix this. I'm going to add information about the gesture placement for both left and right-handed people.

**Comment by ZacharieALES** [comment]
I get the following error when I run the installation command:

```
root@reMarkable:~# sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.6
Connecting to raw.githubusercontent.com (185.199.111.133:443)
wget: note: TLS certificate validation not implemented
writing to stdout
-                    100% |******************************************************************|  4785  0:00:00 ETA
written to stdout

 rM Hacks Installer 
--------------------

Trying to download and install patch: '0.0.6'
Connecting to raw.githubusercontent.com (185.199.109.133:443)
wget: note: TLS certificate validation not implemented
wget: server returned error: HTTP/1.1 404 Not Found
error reading input file
tar: invalid magic
tar: short read
```

If I remove ` _ patch 0.0.6`, the v0.0.5 is installed without error. Did I miss something?

**Comment by ZacharieALES** [comment]
I get the following error when I try to install the new version:

`root@reMarkable:~# sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.6
Connecting to raw.githubusercontent.com (185.199.111.133:443)
wget: note: TLS certificate validation not implemented
writing to stdout
-                    100% |******************************************************************|  4785  0:00:00 ETA
written to stdout

 rM Hacks Installer 
--------------------

Trying to download and install patch: '0.0.6'
Connecting to raw.githubusercontent.com (185.199.108.133:443)
wget: note: TLS certificate validation not implemented
wget: server returned error: HTTP/1.1 404 Not Found
error reading input file
tar: invalid magic
tar: short read
`

If I remove ` _ patch 0.0.6`, version 0.0.5 is installed without error. Did I miss something?
I am using an rm1 (I do not know if this has any influence).

**Comment by mb1986** [comment]
@ZacharieALES, what version of rM software do you have?

**Comment by ZacharieALES** [comment]
Oh I see. I have the 3.7.0.1930. I will update to 3.8.2.1965 and try again.

**Comment by ZacharieALES** [comment]
I tried everything I could and it worked perfectly. Really great update!

**Comment by rudy0ne** [comment]
Everything works for me so far… Although I can’t say for sure about the Staedtler Jumbo because it’s my first time using it on the rM, so not sure if the little quirks I notice were there without the hacks, but it does erase.

Two things I should point out:

— While in the rM Hacks General and Gesture settings, only the first four entries are visible in landscape mode, with no ability to swipe down to access the ones that are cut off.

— And there’s a small typo in the Gesture settings, which says “the two last two pens strokes” instead of just “the last two pen strokes”

Awesome work!!

**Comment by mb1986** [comment]
Thanks for the feedbacks!

- I don't have the Steadtler pencil so let's wait for @digitaldazz who raised the issue.
- Oh, good catch with the landscape mode and settings - I haven't thought about it, raising the issue for one of the future releases.
- Just fixing the typo, it will be fixed in the next release.

Thanks again :heart:

**Comment by mb1986** [comment]
> > Note: I wouldn't write which side the gesture is on, because it's a bit confusing for left-handed people - the bar is on the other side and so are the gestures.
> 
> @PepikVaio, I fully agree with your note. Let me review the entire README.md and fix this. I'm going to add information about the gesture placement for both left and right-handed people.

Is it better now? https://github.com/mb1986/rm-hacks/blob/release/v0.0.6/README.md

**Comment by dreadful-brain** [comment]
Just a huge shout out: You're awesome!!!
I just tested every new feature on my rM2 and it works like a charm.
IMO the config page and the new in doc config are really fantastic.
I'm really impressed of the quality you deliver in this short period of time.
I thank you a lot, you gave me a huge productivity boost on my rM2

**Comment by PepikVaio** [comment]
> > > Poznámka: Na které straně je gesto bych nepsal, protože pro leváky je to trochu matoucí - lišta je na druhé straně a gesta také.
> > 
> > 
> > @PepikVaio, plně souhlasím s Vaší poznámkou. Dovolte mi zkontrolovat celý README.md a opravit to. Doplním informace o umístění gest pro leváky i praváky.
> 
> Je to teď lepší? https://github.com/mb1986/rm-hacks/blob/release/v0.0.6/README.md

Yes, much better.
Maybe it will be useful?

https://github.com/PepikVaio/reMarkable/tree/main/reMarkable_hack/rm-hacks

right_hand
left_hand

**Comment by PepikVaio** [comment]
https://1drv.ms/f/s!AhI1pC-JHcQPg_tc8GoKxVifd1UjQQ?e=50z9Us

Tool display when the rm panel is closed:
Great, you've rotated the pen view when closing the rm panel - it's way better than a rotated pen image.

But I think that when the lasso or  selection eraser tool is selected, the pen strength and pen color should not be displayed.
Only for "eraser" strength strength pen.

What do you think?

**Comment by rudy0ne** [comment]
Hey guys, here are a couple of things I noticed:

[1]
Pen tools, whenever a last used color/stroke gesture is triggered, appear to inherit the color or stroke size of the pen tool that was previously selected if the pen switch was also via gesture. This might work just fine for most pen tools, but results in some weird behavior when it comes to the highlighter: I believe it defaults to yellow highlighter every time when it inherits the previously used pen’s color selection. And the three biggest stroke sizes (5, 8, 13) are probably unusable for a highlighter.


[2]
Last two open documents switching only opens the documents on the last page visited before they were closed. In other words, page swipes are not saved in between document switches if using the gesture. They appear to only be saved whenever you close out the document or use the Recents/Favorites feature.

**Comment by PepikVaio** [comment]
> [2] Přepnutí posledních dvou otevřených dokumentů otevře pouze dokumenty na poslední navštívené stránce před jejich zavřením. Jinými slovy, přejetí stránky se při použití gesta neukládají mezi přepínáním dokumentů. Zdá se, že se uloží pouze při zavření dokumentu nebo použití funkce Poslední/oblíbené.


I confirm.

**Comment by mb1986** [comment]
> [2] Last two open documents switching only opens the documents on the last page visited before they were closed. In other words, page swipes are not saved in between document switches if using the gesture. They appear to only be saved whenever you close out the document or use the Recents/Favorites feature.

Please re-check now (you'll need to reinstall hacks).

**Comment by PepikVaio** [comment]
Funguje to.
Děkuji za rychlou opravu.

**Comment by PepikVaio** [comment]
Additional settings in rm panel "dosument-level"
After restarting the device, it will not retain the desired settings.

If I turn off the clock display, after a reboot I have the clock back.
Other settings (wifi, updates, ...) will keep the settings.

And I think it deserves its own entry in the rm panel :)

**Comment by mb1986** [comment]
> Additional settings in rm panel "document-level" After restarting the device, it will not retain the desired settings.
> 
> If I turn off the clock display, after a reboot I have the clock back. Other settings (wifi, updates, ...) will keep the settings.

Yes, the document-level settings are not preserved between restarts.

**Comment by WieValdi** [comment]
I tested the Stadler Jumbo. The eraser works fine Thank you!!

**Comment by mb1986** [comment]
> I tested the Stadler Jumbo. The eraser works fine Thank you!!

Oh, thank you @WieValdi  for the reply on this, I've got different opinion in https://github.com/mb1986/rm-hacks/issues/46.

**Comment by rudy0ne** [comment]
Any plans to add page numbers in the middle of the toolbar just like they appeared in ddvk-hacks (e.g., 17 of 100)? Battery percentage would also be great to have.

Sorry if it's the wrong place to ask.

**Comment by mb1986** [comment]
> Any plans to add page numbers in the middle of the toolbar just like they appeared in ddvk-hacks (e.g., 17 of 100)? Battery percentage would also be great to have.
> 
> Sorry if it's the wrong place to ask.

Sure, please raise new issues for those.

(I'm about to close this release.)

**Comment by WieValdi** [comment]
> > I tested the Stadler Jumbo. The eraser works fine Thank you!!
> 
> Oh, thank you @WieValdi for the reply on this, I've got different opinion in #46.

Just cross checked the behavior on a different reMarkable and the same Staedtler Noris digital jumbo, and it is also working fine.

**Comment by digitaldazz** [comment]
Just confirming the steadler noris working comment, does it switch to the eraser mode automatically when you use the eraser side and then switch back to the pen mode automatically after use?

**Comment by WieValdi** [comment]
> Just confirming the steadler noris working comment, does it switch to the eraser mode automatically when you use the eraser side and then switch back to the pen mode automatically after use?

yes, it switches to the eraser mode and then switch back

**Pull request merged**
