### PR TITLE
Prepare v0.0.8 release for 3.9.3.1986

### LINKED ISSUE #43: Add support for bookmarks
Thanks a lot for bringing this project back to life.

The one feature that keeps me from updating to v3 is bookmarks, I work with several long reference books that cannot be used conveniently without bookmarks.

I don't know quite how ddvk did it, but from outside it seems that the hack kept a ".bookm" file alongside each document, with the bookmark information.

### LINKED ISSUE #78: Add rM Hacks version number to configuration page
Not a big deal, but thought this additional location (as well as General-->Software, where it is currently displayed) would be a nice touch.

### LINKED ISSUE #79: Feature Request: Hide Page Number
It would be great if the page numbers at the bottom of the page could be hidden.

Sometimes when browsing documents, the content is even at the bottom of the page and then the page bar overlaps the content.

We have a new function to display pages in the panel, so the bottom part could be turned off.

- [x] Hide page numbers

### LINKED ISSUE #84: Toolbar page numbers are misaligned when in left-handed mode
In left-handed mode, the toolbar page numbers implemented in #77 are displayed as follows: The top number is aligned right instead of left, and the bottom number is aligned left instead of right. I feel they should be aligned the same as they are in right-handed mode.

### LINKED ISSUE #85: Feature Request: Better content button integration
Please edit the content button so that it is a separate function, not just a function pulled from another function.

As soon as I open the site overview - the site overview opens - OK
As soon as I open the table of contents - the table of contents opens - OK
When I open the table of contents and select a page and then press the page overview, the table of contents opens :(

I understand why this is happening but it is very confusing.
Can it be modified so that every time I click on the table of contents it opens the table of contents and when I click on the page overview it always opens the page overview?

The second problem, as soon as I open the overview of the pages, I have a back button, I get to the document.
Once I open the table of contents, I also have the back but I get to the page table of contents.
So I have to double tap to get to the document.

- [ ] Modify the buttons to open the correct screen every time
- [ ] Adjust the back button so I can get to the document with one press.

### LINKED ISSUE #87: Increase area to trigger “light sleep” gesture
The area to trigger the “light sleep” gesture implemented in #77 could be a little bigger. Looks like we currently have about 15 mm from the top edge of the screen, but it might be best if it’s like 25 or 30 mm for better accuracy.

### LINKED ISSUE #101: Wi-Fi icon - remove or strikethrough when WiFi is disabled
When the Wi-Fi is disabled, the "empty" (no bars) range icon creates some confusion for me.  I often wonder if the Wi-Fi is on (or is hunting for a signal), and end up going into the menu to find out.

I think it would make more sense to follow widespread mobile phone / tablet conventions on this.  Namely, when Wi-Fi is disabled:

1) remove the icon altogether, OR
2) strikethrough / slash the icon

Thanks for considering my suggestion!

### LINKED ISSUE #105: Battery charging doesn't show in document level
Battery icon in document level not showing device is charging. Thought it was my cable or charger until I closed current document to see that device was indeed charging. Battery icon in bottom of toolbar should indicate when device is charging.

### LINKED ISSUE #112: Feature request - New list view with smaller symbols
Hello,
In the list view, the files are displayed with a preview. In my opinion, this preview wastes space. Space that could be used to display more files/folders. With DDVK there was such a possibility. Could this also be integrated into the RM hacks?
Thank you 
Sample:
Sample

### LINKED ISSUE #118: Feature Request: Alphabetize tags list
When viewing all tags, I think it would be useful to see them in alpha order.

### LINKED ISSUE #123: Feature request: option to disable auto straight lines
As the title says. I have recently experienced unwanted straight lines while I was sketching, I sometimes draw curves very slowly and I have experienced the Remarkable convert these curves to straight lines when I didn't want to, about 4 or 5 times during the making of a detailed sketch. So I'd very much appreciate if this feature could be disabled at will.
Thank you and keep up the good work, these hacks are a godsend for many of us :).

### PR DESCRIPTION
**Pull request by mb1986**
**Please ensure you've backed up your bookmarks before applying _v0.0.8_! To do so, download the `*.bookm` files from the `/home/root/.local/share/remarkable/xochitl/` directory and store them in a secure location.**

---

### New features:

- Bookmarks feature (closes #43)
  - Tap in the top corner opposite the toolbar to toggle a bookmark for the current page.
  - Long press in the top corner opposite the toolbar to create a named bookmark or to change the name of an existing one.
  - New toolbar bookmarks button showing all bookmarks in the currently open document.
  - Long press the bookmarks toolbar button to toggle a bookmark for the current page.
  - Long press the bookmark grid item from the bookmarks menu to rename the bookmark.
  - New configuration section for bookmarks in the settings.
- Compressed list for documents navigation (closes #112).
- Page numbers at the bottom of document pages are now hidden (closes #79).
- Expanded the area for the 'swipe up to sleep' gesture (closes #87).
- Toolbar WiFi icon is now hidden when the WiFi connection is disabled (closes #101).
- The toolbar battery icon changes to a lightning icon when the device is charging (closes #105).
- Improved behavior of the table of contents and page overview toolbar buttons (closes #85).
- Tags are now shown in alphabetical order in the Menu/Tags view (closes #118).
- Document-level toggle to disable the straight lines feature (closes #123).
- The hacks version is also displayed in the hacks configuration view header (closes #78).

### Bug fixes:

- Page numbers toolbar button is now properly aligned in left-handed mode (closes #84).

### Known issues:

- The bookmarks toolbar button does not fit in the landscape mode.

---

**For testing, please run the following command on your device:**

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/release/v0.0.8-3.9.3.1986/install.sh -O-)"
```

### CODE REVIEW

**Comment by PepikVaio** [comment]
> **_Před použitím verze 0.0.8_ se ujistěte, že jste si zálohovali své záložky ! Chcete-li tak učinit, stáhněte si `*.bookm`soubory z `/home/root/.local/share/remarkable/xochitl/`adresáře a uložte je na bezpečné místo.**
> 

This is the first time you've asked for an advance.
I understand that a hack is always a risk but why the concern now?

**Comment by mb1986** [comment]
> This is the first time you've asked for an advance. I understand that a hack is always a risk but why the concern now?

The bookmarks feature reads and writes `*.bookm` files where your bookmarks are stored. I've implemented this feature differently than ddvk, assigning bookmarks to page ids and not to page numbers only. It helps in situations where we move, add, or remove pages in a document. The bookmarks loader, however, is backward compatible and should be able to read bookmarks created by the ddvk hacks version. Nonetheless, I don't want you to lose your bookmarks in case of any bug I've introduced.

**Comment by PepikVaio** [comment]
OK I do not have any bookmarks from DDVK.
But i backup all file xochitl.

**Comment by PepikVaio** [comment]
**Testing**

#43 - it works (I will elaborate more in the next post).
Perfect that I can turn off the corner gesture but still use the bookmarks :)

#112 - Absolutely perfectly implemented (I couldn't think of a better place)

#79 - Works great, just as I imagined.

#87 - Worked great for me before the update (now it works great too).

#101 - Works

#105 - Great (that's nice)

#85 - Great, thank you so much for that (that's awesome)

#118 - This is a great feature, it looks so natural (like it should have been from the beginning)

#123 - It works great (may be very useful for some people - I probably wouldn't have thought of it)

#78 - Nice

#84 - I didn't notice how it was before the fix.




> *The bookmarks toolbar button does not fit in the landscape mode. 

I'll elaborate more in the next post.

**Comment by PepikVaio** [comment]
Bookmarks

I bought Supernote 2 days ago and it is true that it has some nice features (maybe I would use some of it).

The bookmarks feature is very well implemented (in my opinion)

1. tapping on the icon opens a window(in the top third and nicely in the middle - nice to look at) where you can type in the name of the bookmark (a pre-made name from the table of contents).
2. tapping on the bookmark icon deletes the bookmark (simple as that)

Bookmarks list has a dedicated button where it is displayed along with other items (bookmarks, keywords, table of content)
Plus, when there's a lot of stuff, you can turn the pages and I find that really cool.

IMG_3191
IMG_3192
IMG_3193
IMG_3194
IMG_3195
IMG_3196

**Comment by PepikVaio** [comment]
**But I think this would be difficult to create or time consuming.
What I think would be great, though, is to make the bookmark function reMarkable style.**

I mean it like this:

One click on a bookmark opens a menu just like the labels (exactly the same - design much nicer than bookmarks now).

Bookmarks list at the top in the same design as the labels (nicer and doesn't take up as much space as square icons - icons get bigger according to the text - see photo 1).

At the bottom have the option to create a new bookmark (the "+" icon)
When you click to create a bookmark, make it in the same design as the tags (see photo 2 and 3)

I guess I don't need a bookmark icon in the top menu when I have an icon in the panel (optional).
I probably don't need a page number next to the bookmark name (optional).
I would leave the option for even a long press for a quick bookmark without a name (or just the page number).

IMG_3197

IMG_3198
IMG_3199

**Comment by PepikVaio** [comment]
**Known issues:
The bookmarks toolbar button does not fit in the landscape mode.**

I have 2 suggestions on this issue:

1. Shrinking the icons throughout the panel, this way more icons can fit on the panel in both portrait and landscape.
Inspiration again from Supernote.
The width of the remarkable icons is 11mm (104px) and I think this is unnecessarily large (reMarkable itself has already shrunk the icons once).
For supernote the icon is 9 mm (it doesn't seem like a big difference but it is a huge difference).

Number of icons in portrait (landscape):
reMarkable = 18
Supernote = 20

Number of icons in portrait (landscape):
reMarkable = 13.5
Supernote = 16 (I found that it changes the height to always fill the entire section from top to bottom)

**2. Another option is to choose what we want on the panel (finally, a customizable remarkable panel) :)**


But I think I would start by making it smaller.
When I switch from reMarkable to supernote now, the difference is huge to look at.

**Comment by rudy0ne** [comment]
**BOOKMARKS** — Oh yeah, I’m loving this more aesthetically-pleasing bingo card! It’s very fast jumping from one bookmark to another, even in a very large document!!! Please don’t change a thing, with the exception of a fix for the following two:

- Thankfully, despite only half the toolbar icon showing, the bookmarks can still be displayed while in landscape (and with the Type Folio), but you do have to be very precise when tapping the icon. I currently have to use the marker to do it properly.

- When bookmarks corner tap is disabled in settings the long-press gesture which adds or renames a bookmark still remains. Can that also be disabled somehow?

**COMPRESSED DOCUMENTS LIST** — Very nice!

**PAGE NUMBERS HIDDEN** — Great for distraction-free reading, especially when those numbers don’t match the in-document page numbers.

**SLEEP GESTURE IMPROVEMENT** — Much more responsive now, thank you!

**TOC / OVERVIEW PAGE IMPROVEMENT** — Awesome! Now works as it always should have!

**TAGS IN ALPHABETICAL ORDER** — It appears that they are case-sensitive, so all lower-case tags appear after all the capitalized tags. For example, “ac” appears after “Bh” 

- Also, it would be great if the popup tags list in the toolbar were alphabetized as well.

**PAGE NUMBERS IN TOOLBAR PROPERLY ALIGNED** — Thank you!

**Comment by rudy0ne** [comment]
> **Bookmarks**
> 
> I bought Supernote 2 days ago and it is true that it has some nice features (maybe I would use some of it).
> 
> The bookmarks feature is very well implemented (in my opinion)
> 
> 1. tapping on the icon opens a window(in the top third and nicely in the middle - nice to look at) where you can type in the name of the bookmark (a pre-made name from the table of contents).
> 2. tapping on the bookmark icon deletes the bookmark (simple as that)
> 
> Bookmarks list has a dedicated button where it is displayed along with other items (bookmarks, keywords, table of content) Plus, when there's a lot of stuff, you can turn the pages and I find that really cool.
> 


That side panel with all the tabs would make navigating a bookmarks table of contents too slow of a process. Especially with something like my 1300-page thesaurus. I wanna be able to just do a quick tap on the toolbar icon followed by a quick tap on the bingo card and then keep it moving 😝

I think the Supernote is meant to be used a little differently than the reMarkable. It forces you to sort of slow down because of all the features it has. I used to own both, A5X and A6X, but then switched to the rM2 with Type Folio eight months ago. But for mind-mapping and concept art I’ve got my eyes set on the future A4X.

And for the most part, I'm happy with Michał's implementation of the bookmarks popup list. The items are easy to read, and they're big enough to tap quickly with your finger when jumping between bookmarks.

**Comment by Kelvin88** [comment]
Like new features and fixes 👍. 

> I bought Supernote 2 days ago and it is true that it has some nice features (maybe I would use some of it).
Had A5x briefly, like some of advanced features of SN especially 2 finger eraser gesture. Prefer look & feel of rM2, plus writing feel is much better IMO on rM2. rm-Hacks makes it even better.

**Comment by PepikVaio** [comment]
Well I think the bingo look is crazy. 
If it was in the look of the tags, it would fit the reMarkable style (like the original).
Speed exactly the same.

**Comment by PepikVaio** [comment]
Please disable the long press gesture when I have short press disabled.

Otherwise I get the left hand tab renaming on :(

**Comment by mb1986** [comment]
Thank you very much for all the comments!

I am happy you did not find any huge bugs there :) @ard0gg, thanks for the regression testing!

@PepikVaio, I've created a new issue to rethink how bookmarks should be displayed. Let's discuss it there and conclude what it should look like and how (#127).

@Kelvin88, @rudy0ne, I am glad you mostly like the changes.

I hope that the changes in issue #88 will address the issue of limited space on the toolbar.

I am also planning to disable the bookmark corner long press as you've suggested, in just a couple of minutes:

> When the bookmarks corner tap is disabled in settings, the corner icon long-press gesture that adds or renames a bookmark still remains. Can that also be disabled somehow?

> Please disable the long press gesture when I have short press disabled. Otherwise, I get the left-hand tab renaming on :("

And right after that, I'd like to merge version 0.0.8!

**Comment by mb1986** [comment]
> Let me "fix" that in the evening.

Fixed, you may reinstall the hacks to see the effect.

**Comment by PepikVaio** [comment]
@mb1986 You're the best.
Thank you for opening the suggestion to change the look of the bookmarks, it would be nice.

**Pull request merged**
