### PR TITLE
Fix #151

### LINKED ISSUE #151: Script improvements: No update
Maybe it would be a good idea, after installing the hack, to disable automatic updates?

That option is in the hack, so I think the changes would be enough just to have the settings written down.

It would be nice for people who forget to turn it off manually.

Ideally information in the terminal that automatic updates are now disabled so they don't lose hacks.

### PR DESCRIPTION
**Pull request by Eeems**
This change asks the user if they would like to disable automatic update (if it's enabled).

This is untested, but in theory should work.

### CODE REVIEW

**Comment by atngames** [comment]
@mb1986 did You look at this ?

**Comment by mb1986** [comment]
Not yet. Have you?

**Comment by atngames** [comment]
Nope :)
I'll try to look at this pretty soon @Eeems

**Review by atngames — APPROVED** [review]
@mb1986 @Eeems I tested it, works perfectly. Code seem fine flawless to me...

**Review by atngames — APPROVED** [review]

**Comment by Eeems** [comment]
> @mb1986 @Eeems I tested it, works perfectly. Code seem fine flawless to me...

Awesome! It isn't often code I write but don't test survives first contact :laughing:

**Comment by mb1986** [comment]
Wonderful, merging it then, thanks!

**Pull request merged**
