### PR TITLE
Prepare v0.0.7 release for 3.8.2.1965

### LINKED ISSUE #51: Settings overflow the display in the landscape mode

### LINKED ISSUE #52: Show pen thickness and color indicators only for the tools which make use of it
I think that when the "lasso" or  "selection eraser" tool is selected, the pen strength and pen color should not be displayed.
Only for "eraser" strength strength pen.

What do you think?

_Originally posted by @PepikVaio in https://github.com/mb1986/rm-hacks/issues/49#issuecomment-1826350156_

### LINKED ISSUE #55: Feature request: Page numbers on the toolbar
Please add page numbers in the middle of the toolbar similar to in ddvk-hacks (e.g., 17 of 100).

And thank you for the option to toggle things off, as I’m sure this feature may be distracting to some while very useful to others.

### LINKED ISSUE #56: Feature request: Battery percentage in document
In-document battery percentage would be very helpful. Perhaps just above the clock, or in the middle of the toolbar along with the page number.

Thanks again for the excellent work!

### LINKED ISSUE #57: Feature Request: Force refresh gesture

### LINKED ISSUE #58: Gesture to swap the last two pen thicknesses + eraser: Bug
Version: 0.0.6

I found a bug in the swap pen thickness gesture after using the eraser. Here's the description:

1) Pen thickness 1: write
2) Select thickness 5: write
3)  One finger down: switch to thickness 1, write
4) One finger down: switch to thickness 5, write
5) Press Lamy erase button or manually select eraser with thickness 2 and delete
6) One finger down: switch to thickness 2: NOT 1 as it should

**It seems that it recalls the last thickness of the tool used, not the last thickness of the pen.**

Many thanks for putting up this wonderful project.

### LINKED ISSUE #65: Feature request: Table of contents button in the toolbar
Continuing with old Ddvk's feature that would be great to see in a form or another in this project : to have a shortcut button to open table of contents directly from the toolbar, instead of having to go to the overview first. It really helps navigation in heavy pdf documents. Maybe could it be disabled in rm-hacks settings to not fill the quick menu in the toolbar ?

### LINKED ISSUE #74: Feature request: In-document button to trigger “light sleep”
Light sleep, which can be turned on in the security settings, puts the device to sleep after 20 minutes of inactivity and displays whatever document page was left open. It’s very handy for leaving a to-do list open while conserving battery.

However, there is currently no way to force this since pressing the power button puts it to sleep on the screensaver.

### PR DESCRIPTION
**Pull request by mb1986**
### New features:

- Toolbar button showing the current page and the page count, clicking it opens fast page scroll (see #55).
- Battery level and WiFi signal strength indicators available on the bottom of the toolbar (closes #56).
- Screen refresh trigger via five-finger tap - natively available but disabled by experimental flag (closes #57).
- Additional table-of-contents toolbar button (closes #65).
- Enable sleep mode by swiping up from the top of the screen (light or deep sleep selectable in Settings/Security) (closes #74).
- Display `...zzZ` in the top right corner during light sleep mode instead of a big black banner (see #74).

### Bug fixes:

- Configuration items may be scrolled vertically (closes #51).
- Pen thickness and color indicator show only for the tools that make use of them (closes #52).
- All the tools remember last two strokes and colors separately (closes #58).

### Other changes:

- Document-level clock moved from the bottom to the top of the toolbar.
- Make clock toggle option permanent between restarts.
- Changed names of document-level toggles (i.e. remove "Disabled" and "Enabled" words).

---

```sh
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.7
```

### CODE REVIEW

**Comment by PepikVaio** [comment]
Hi, looks good. 

I'll test all the functions tomorrow.

**Comment by rudy0ne** [comment]
Oh, I didn't know it was good to test out already!

**Comment by mb1986** [comment]
Yeap, your feedback is very appreciated as always :)

**Comment by babluc** [comment]
`reMarkable: ~/ sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.7
Connecting to raw.githubusercontent.com (185.199.111.133:443)
wget: note: TLS certificate validation not implemented
writing to stdout
-                    100% |****************************************************************************************************|  4785  0:00:00 ETA
written to stdout

 rM Hacks Installer 
--------------------

Trying to download and install patch: '0.0.7'
Connecting to raw.githubusercontent.com (185.199.110.133:443)
wget: note: TLS certificate validation not implemented
wget: server returned error: HTTP/1.1 404 Not Found
error reading input file
tar: invalid magic
tar: short read
`

I get this error. What am I doing wrong?

**Comment by PepikVaio** [comment]
What version of sw do you have?
This version of hooks is available for:

**Comment by PepikVaio** [comment]
New features:

#55 - Okay
I find the click function useless unless the feature is expanded in the future..

#56 - Okay
I think it's overpaid, but it's great that I can turn it off.

#57 - OK works great.
Could the feature be extended to disable refresh and only refresh myself? Like super fast mode? Because sometimes screen flickering is annoying. It would be a great feature (disable completely, option after 10, 20, 30, ... pages - in settings???)

#65 - OK
I'm glad it only shows when content is available - cool.
Would it be possible to adjust?
When I click on the icon, I get to the table of contents - I select a page - OK. But if I then click on the icon from rm "Page overview" - I get to the content - would it be possible to display what it has? So a list of sites?

#74 - OK - works great.
Maybe a modification to split the gesture function and the "...zzZ" display?
Someone doesn't need a gesture but would like to "...zzZ" - Maybe unnecessary, but now it's either both or nothing. Someone may be annoyed by the gesture, but he would like "...zzZ".

Error correction:

#51 - I don't have a keyboard, but I can scroll.

#52 - Okay
Fixed - thank you.

Maybe another fix:
1. When I change the color of the pen with a gesture, and I have black and gray selected, it shows white for a moment when switching:
Black, swipe, white and immediately gray.
Then:
Swipe, white and immediately black.
2. When switching the thickness of the pen with a gesture, the thickness icon moves back and forth (it's a detail but distracting :) I'm a detailer :) )

#58 - Not tested

Other changes:
I preferred the clock down - can it be optional?

Settings hold between reboots - Great, thanks, works great.


_Changed names of document-level switches (ie remove the words "Disabled" and "Enabled")._
I do not know what it means?

**Comment by rudy0ne** [comment]
Everything works great from what I can tell so far.


— First of all, I absolutely love how each tool now saves the last two used stroke sizes and colors independently! This is now perfect for annotating PDFs. A huge thank you!

— Love the battery level and WiFi indicators, very useful to me!

— Refresh gesture works like a charm, and with the same hand that I’m holding the pen. Actually a lot more ergonomic than I expected.

— The light sleep mode gesture is brilliant! You left out that it’s a “one finger” swipe in the description above. But you did include that detail in the rm-hacks settings. (By the way, the …zzZ is nice but would still prefer a tiny coffee cup 😁 or at least the padlock icon, maybe an option?)

— The vertical scroll to access all rm-hacks settings works as intended while in the Type Folio’s landscape mode.



**Page Numbers**

At first glance I thought you made the page thumbnails bigger while using the fast page scroller, but it seems that’s how it was before… I’m currently using the fast page scroller in conjunction with the table of contents button on my large PDF thesaurus, but for large documents without a table of contents:

— I’m curious if it’s possible to implement my suggestion of narrowing the amount of pages shown on the fast page scroller bar to about only 10 or 20 for more precision when navigating large documents? _Maybe that’s what tapping the page numbers could do, give you a “zoomed” view of the fast page scroller bar, while the one-finger up from the bottom gesture would still give you the full bar of pages._ I hope that makes sense.

— And finally, in left-handed mode the top page number is aligned right instead of left, and the bottom number is aligned left instead of right. I feel they should be aligned the same as they are in right-handed mode. What do you think?  

Incredible work overall!

**Comment by PepikVaio** [comment]
> — Gesto režimu lehkého spánku je skvělé! Ve výše uvedeném popisu jste vynechali, že jde o přejetí „jedním prstem“. Tento detail jste ale zahrnuli do nastavení rm-hacks. (Mimochodem,…zzZ je pěkný, ale stále by preferoval malý šálek kávy 😁 nebo alespoň ikonu visacího zámku, možná možnost?)
> 

No padlock, please :)
A cup of coffee - maybe.

For me, "...zzZ" is great, because if instead of "...zzZ" there is an image and reMarkable will be put to sleep on the main screen, it covers the magnifying glass icon and that would be ugly - it's OK this way and "...zzZ" will not hide anything.

Optional would be great but how to upload an image?
And maybe it would be unnecessarily complicated?

**Comment by rudy0ne** [comment]
My preference for an icon is that the "...zzZ" is text, which I use a lot, and at first glance from a few feet away I may not immediately notice it's in light sleep compared to if it were an icon that even from across the room may be recognizable.

I believe Michał mentioned that there's a padlock font icon. No need to go through the trouble of using an actual image.

Not sure about the main page, since I was only able to use the light sleep gesture while inside a document and I just assumed that's the only way it was meant to work, which is totally fine for my use.

**Comment by PepikVaio** [comment]
> Nejsem si jistý hlavní stránkou, protože jsem byl schopen použít gesto lehkého spánku pouze v dokumentu a předpokládal jsem, že je to jediný způsob, jak to mělo fungovat, což je pro mé použití naprosto v pořádku.

Leave reMarkable for 20 minutes on the main page and you'll see it go to sleep and there will be "...zzZ" if there was an image, it will overlay the magnifier.

**Comment by rudy0ne** [comment]
I understand. But I guess I just don't have as much use for light sleep on the main page, at least not as much as I do when there's an open document. Although I might still use the light sleep gesture on the main page if given the option. 

And if emojis would work these aren't too bad 😴💤

**Comment by PepikVaio** [comment]
I noticed one bug that is not related to the 0.0.7 update

When I copy an object, a bar appears at the bottom telling me that I have copied an object - then it is not possible to gesture from the bottom of the screen to switch to the last file.

**Comment by rudy0ne** [comment]
— The area to trigger the “light sleep” gesture could be a little bigger. Looks like we currently only have about 15 mm from the top edge of the screen, might be best if it’s like 25 or 30 mm.

**Comment by WehZet** [comment]
is v0.0.7 also working with RM2 3.8.3.1976 ?
got the update last week

**Review by ard0gg — APPROVED** [review]
Tested new features, bug fixes and other changes and they work as described.

**Comment by mb1986** [comment]
@PepikVaio, thank you for the feedback!

> New features:
> 
> #55 - Okay I find the click function useless unless the feature is expanded in the future..

Sure, thanks, I'll keep the issue open and will try to apply on of the ideas.

> #56 - Okay I think it's overpaid, but it's great that I can turn it off.
> 
> #57 - OK works great. Could the feature be extended to disable refresh and only refresh myself? Like super fast mode? Because sometimes screen flickering is annoying. It would be a great feature (disable completely, option after 10, 20, 30, ... pages - in settings???)

I don't know if it is possible, raise the issue and I'll verify it.

> #65 - OK I'm glad it only shows when content is available - cool. Would it be possible to adjust? When I click on the icon, I get to the table of contents - I select a page - OK. But if I then click on the icon from rm "Page overview" - I get to the content - would it be possible to display what it has? So a list of sites?

I think it is a native behavior that when you select the pages view, then the table of contents view, and you select an entry from the table of contents, then coming back to the pages shows the table of contents view. Am I right?
Nonetheless, I could change it that selecting the pages view shows always the pages view. 

> #74 - OK - works great. Maybe a modification to split the gesture function and the "...zzZ" display? Someone doesn't need a gesture but would like to "...zzZ" - Maybe unnecessary, but now it's either both or nothing. Someone may be annoyed by the gesture, but he would like "...zzZ".

I am sure there are two separate options for those (swipe configuration views to scroll).

> Error correction:
> 
> #51 - I don't have a keyboard, but I can scroll.
> 
> #52 - Okay Fixed - thank you.
> 
> Maybe another fix:
> 
> 1. When I change the color of the pen with a gesture, and I have black and gray selected, it shows white for a moment when switching:
>    Black, swipe, white and immediately gray.
>    Then:
>    Swipe, white and immediately black.

Yes, this is how e-paper refreshes it, cannot do anything about it.

> 2. When switching the thickness of the pen with a gesture, the thickness icon moves back and forth (it's a detail but distracting :) I'm a detailer :) )

Cannot reproduce it.

> #58 - Not tested
> 
> Other changes: I preferred the clock down - can it be optional?

Yes, it should be easy one :)

> Settings hold between reboots - Great, thanks, works great.
> 
> _Changed names of document-level switches (ie remove the words "Disabled" and "Enabled")._ I do not know what it means?

I've changed the names of document-level toggles - for example `WiFi Enabled` or `WiFi Disabled` there is `WiFi Connection` now.

**Comment by mb1986** [comment]
@rudy0ne, thank you for the feedback!

> Everything works great from what I can tell so far.
> 
> — First of all, I absolutely love how each tool now saves the last two used stroke sizes and colors independently! This is now perfect for annotating PDFs. A huge thank you!
> 
> — Love the battery level and WiFi indicators, very useful to me!
> 
> — Refresh gesture works like a charm, and with the same hand that I’m holding the pen. Actually a lot more ergonomic than I expected.
> 
> — The light sleep mode gesture is brilliant! You left out that it’s a “one finger” swipe in the description above. But you did include that detail in the rm-hacks settings. (By the way, the …zzZ is nice but would still prefer a tiny coffee cup 😁 or at least the padlock icon, maybe an option?)

I see, I'll try to add some configuration :)

> — The vertical scroll to access all rm-hacks settings works as intended while in the Type Folio’s landscape mode.
> 
> **Page Numbers**
> 
> At first glance I thought you made the page thumbnails bigger while using the fast page scroller, but it seems that’s how it was before… I’m currently using the fast page scroller in conjunction with the table of contents button on my large PDF thesaurus, but for large documents without a table of contents:
> 
> — I’m curious if it’s possible to implement my suggestion of narrowing the amount of pages shown on the fast page scroller bar to about only 10 or 20 for more precision when navigating large documents? _Maybe that’s what tapping the page numbers could do, give you a “zoomed” view of the fast page scroller bar, while the one-finger up from the bottom gesture would still give you the full bar of pages._ I hope that makes sense.

It may be possible, I'll check that.

> — And finally, in left-handed mode the top page number is aligned right instead of left, and the bottom number is aligned left instead of right. I feel they should be aligned the same as they are in right-handed mode. What do you think?

Oh, you are right, I've not noticed it... Could you please raise the issue that I'll remember to fix it?

> Incredible work overall!

**Comment by PepikVaio** [comment]
> > #57 - OK funguje skvěle. Mohla by být funkce rozšířena tak, aby zakázala obnovení a obnovila se pouze já? Líbí se vám super rychlý režim? Protože někdy je blikání obrazovky nepříjemné. Byla by to skvělá funkce (úplně zakázat, možnost po 10, 20, 30, ... stránkách - v nastavení???)
> 
> Nevím, jestli je to možné, upozorněte na problém a já to ověřím.

OK, I'll create a request.
------------------------------------------------------------------------

> > #65 - OK Jsem rád, že se zobrazuje pouze tehdy, když je dostupný obsah - skvělé. Bylo by možné upravit? Když kliknu na ikonu, dostanu se do obsahu - vyberu stránku - OK. Ale když pak kliknu na ikonku z rm "Přehled stránek" - dostanu se k obsahu - šlo by zobrazit to co má? Takže seznam stránek?
>
> Myslím, že je přirozené chování, že když vyberete zobrazení stránek, pak zobrazení obsahu a vyberete položku z obsahu, pak se při návratu na stránky zobrazí zobrazení obsahu. Mám pravdu? Mohl jsem to však změnit tak, že výběr zobrazení stránek vždy zobrazí zobrazení stránek.

OK, I'll create a request with a video.
------------------------------------------------------------------------

> > #74 - OK - funguje skvěle. Možná úprava pro rozdělení funkce gest a zobrazení "...zzZ"? Někdo gesto nepotřebuje, ale rád by "...zzZ" - Možná zbytečné, ale teď je to buď obojí, nebo nic. Někomu to gesto může vadit, ale chtělo by to „...zzZ“.
> 
> Jsem si jistý, že pro ně existují dvě samostatné možnosti (přecházení zobrazením konfigurace přejetím prstem).

My fault, I didn't notice I could swipe down the page.
------------------------------------------------------------------------

> > #52 - Dobře Opraveno - děkuji.
> > Možná další oprava:
> > 
> > 1. Když gestem změním barvu pera a mám vybranou černou a šedou, tak se při přepínání na chvíli zobrazí bílá: 
> >    Černá, swipe, bílá a hned šedá. 
> >    Poté: 
> >    Přejeďte, bílá a hned černá.
> 
> Ano, takhle to e-papír osvěžuje, nemůže s tím nic dělat.

OK
------------------------------------------------------------------------

> > 2. Při přepínání tloušťky pera gestem se ikona tloušťky pohybuje tam a zpět (je to detail, ale ruší pozornost :) Jsem detailista :) )
> 
> Nelze to reprodukovat.

OK
------------------------------------------------------------------------

> > Další změny: Preferoval jsem snížení hodin - může to být volitelné?
> 
> Ano, mělo by to být snadné :)

OK - Great
------------------------------------------------------------------------

> > _Změněné názvy přepínačů na úrovni dokumentu (tj. odstranit slova „Zakázáno“ a „Povoleno“). _nevím, co to znamená?
> 
> Změnil jsem názvy přepínačů na úrovni dokumentu – například `WiFi Enabled`nebo `WiFi Disabled`je `WiFi Connection`nyní.

OK - Great
------------------------------------------------------------------------

**Pull request merged**
