### PR TITLE
Prepare install and readme for v0.0.5-3.8.2.1965

### LINKED ISSUE #44: rM 3.8.2.1965
I see rM has started rolling out version 3.8 of the software. I don't have it on my device yet, but once I get it, I'll begin preparing the hacks. To avoid losing them, please disable automatic updates for now.

### PR DESCRIPTION
**Pull request by mb1986**
Hacks for 3.8.2.1965 are around the corner. You may test them right now by issuing:

```shell
sh -c "$(wget https://raw.githubusercontent.com/mb1986/rm-hacks/main/install.sh -O-)" _ patch 0.0.5
```

Your feedback is highly appreciated!

Closes #44

### CODE REVIEW

**Comment by digitaldazz** [comment]
Many thanks, all seems to work apart from my steadler pencil not erasing automatically using the erasure side.

**Comment by mb1986** [comment]
> Many thanks, all seems to work apart from my steadler pencil not erasing automatically using the erasure side.

Did it work in **3.7** with hacks applied?

**Comment by digitaldazz** [comment]
Sorry, I do not know as this is the first time I have used your tool. It
used to work with the ddvk qt plugin.

**Comment by mb1986** [comment]
Have you selected to install the ddkv's stylus plugin during the hacks installation?

**Comment by digitaldazz** [comment]
Yes, and also the original ddvk.

**Comment by PepikVaio** [comment]
Everything seems fine. The problems that were in the previous version still persist - I know it will be solved in version 0.0.6.
Thank you very much.

**Comment by atngames** [comment]
Everything works as intended for me.

**Review by atngames — APPROVED** [review]
Seems to work !

**Pull request merged**
